name: songer
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4  # SQLite database package
  path: ^1.8.0       # For constructing file paths
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sqflite_common_ffi: ^2.3.3+1
  path_provider: ^2.1.4
  file_picker: ^5.0.0
  file_selector: ^0.8.0
  audiotags: ^1.4.1
  get_it: ^8.0.0
  just_audio: ^0.9.42
  audio_session: ^0.1.21
  just_audio_windows: ^0.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true